### ISSUE TITLE
Check work stability if Redis shut downed

### ISSUE THREAD

**Issue by EvilLord666** [Wissance/Ferrum#38]
Check how would behave `Ferrum` if we stop `Redis` server, it shouldn't crashed it should respond with something like "Data Storage is not ready, please try again later", and work when storage is Up

In this task i also take some additional works:
* [x] add typical error for `DataStorageNotAvailable`
* [x] add more typical errors 4 determine what happened (`ObjectNotFoundError` and others), this point solves issue: #22 
* [x] working with typical errors (previous list item) brake me a lot of `manager` methods: Have to implement minimal set of tests (partially solves issue #62 
* [x] I should also make come clean-up in `Dockerfile` && `docker-compose` : add permanent name for containers, volumes and so on
* [x] working on docker compose i change to init redis via sh. script (not using python) #44  
* [x] test all method on availability

**Comment by EvilLord666** [comment]
Left only following things:
* [ ] manual check app work on `Redis` shutdown / switch on
* [ ] save script with data init to volume, make permanent volume name 4 `ferrum_webapi`
